### ISSUE TITLE
Another error logging an error

### ISSUE THREAD

**Issue by ddugovic** [ShailChoksi/lichess-bot#163]
Looks very similar to #148 , possibly a regression.

```Dec 24 23:11:46 vps178028 python3[934]: 2018-12-24 23:11:46 __main__[1175] ERROR Terminating client due to connection error
Dec 24 23:11:46 vps178028 python3[934]: Traceback (most recent call last):
Dec 24 23:11:46 vps178028 python3[934]:   File "/home/turing/.local/lib/python3.6/site-packages/urllib3/response.py", line 601, in _update_chunk_length
Dec 24 23:11:46 vps178028 python3[934]:     self.chunk_left = int(line, 16)
Dec 24 23:11:46 vps178028 python3[934]: ValueError: invalid literal for int() with base 16: b''
Dec 24 23:11:46 vps178028 python3[934]: During handling of the above exception, another exception occurred:
Dec 24 23:11:46 vps178028 python3[934]: Traceback (most recent call last):
Dec 24 23:11:46 vps178028 python3[934]:   File "/home/turing/.local/lib/python3.6/site-packages/urllib3/response.py", line 360, in _error_catcher
Dec 24 23:11:46 vps178028 python3[934]:     yield
Dec 24 23:11:46 vps178028 python3[934]:   File "/home/turing/.local/lib/python3.6/site-packages/urllib3/response.py", line 666, in read_chunked
Dec 24 23:11:46 vps178028 python3[934]:     self._update_chunk_length()
Dec 24 23:11:46 vps178028 python3[934]:   File "/home/turing/.local/lib/python3.6/site-packages/urllib3/response.py", line 605, in _update_chunk_length
Dec 24 23:11:46 vps178028 python3[934]:     raise httplib.IncompleteRead(line)
Dec 24 23:11:46 vps178028 python3[934]: http.client.IncompleteRead: IncompleteRead(0 bytes read)
Dec 24 23:11:46 vps178028 python3[934]: During handling of the above exception, another exception occurred:
Dec 24 23:11:46 vps178028 python3[934]: Traceback (most recent call last):
Dec 24 23:11:46 vps178028 python3[934]:   File "/home/turing/.local/lib/python3.6/site-packages/requests/models.py", line 750, in generate
Dec 24 23:11:46 vps178028 python3[934]:     for chunk in self.raw.stream(chunk_size, decode_content=True):
Dec 24 23:11:46 vps178028 python3[934]:   File "/home/turing/.local/lib/python3.6/site-packages/urllib3/response.py", line 490, in stream
Dec 24 23:11:46 vps178028 python3[934]:     for line in self.read_chunked(amt, decode_content=decode_content):
Dec 24 23:11:46 vps178028 python3[934]:   File "/home/turing/.local/lib/python3.6/site-packages/urllib3/response.py", line 694, in read_chunked
Dec 24 23:11:46 vps178028 python3[934]:     self._original_response.close()
Dec 24 23:11:46 vps178028 python3[934]:   File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
Dec 24 23:11:46 vps178028 python3[934]:     self.gen.throw(type, value, traceback)
Dec 24 23:11:46 vps178028 python3[934]:   File "/home/turing/.local/lib/python3.6/site-packages/urllib3/response.py", line 378, in _error_catcher
Dec 24 23:11:46 vps178028 python3[934]:     raise ProtocolError('Connection broken: %r' % e, e)
Dec 24 23:11:46 vps178028 python3[934]: urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
Dec 24 23:11:46 vps178028 python3[934]: During handling of the above exception, another exception occurred:
Dec 24 23:11:46 vps178028 python3[934]: Traceback (most recent call last):
Dec 24 23:11:46 vps178028 python3[934]:   File "/home/turing/lichess-bot/lichess-bot.py", line 57, in watch_control_stream
Dec 24 23:11:46 vps178028 python3[934]:     for line in response.iter_lines():
Dec 24 23:11:46 vps178028 python3[934]:   File "/home/turing/.local/lib/python3.6/site-packages/requests/models.py", line 794, in iter_lines
Dec 24 23:11:46 vps178028 python3[934]:     for chunk in self.iter_content(chunk_size=chunk_size, decode_unicode=decode_unicode):
Dec 24 23:11:46 vps178028 python3[934]:   File "/home/turing/.local/lib/python3.6/site-packages/requests/models.py", line 753, in generate
Dec 24 23:11:46 vps178028 python3[934]:     raise ChunkedEncodingError(e)
Dec 24 23:11:46 vps178028 python3[934]: requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
Dec 24 23:11:46 vps178028 python3[934]: 2018-12-24 23:11:46 backoff[1175] INFO Backing off watch_control_stream(...) for 0.2s (SystemExit)
Dec 24 23:11:47 vps178028 python3[934]: 2018-12-24 23:11:47 backoff[1175] ERROR Giving up watch_control_stream(...) after 2 tries (json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0))
Dec 24 23:11:47 vps178028 python3[934]: Process Process-2:
Dec 24 23:11:47 vps178028 python3[934]: Traceback (most recent call last):
Dec 24 23:11:47 vps178028 python3[934]:   File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
Dec 24 23:11:47 vps178028 python3[934]:     self.run()
Dec 24 23:11:47 vps178028 python3[934]:   File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
Dec 24 23:11:47 vps178028 python3[934]:     self._target(*self._args, **self._kwargs)
Dec 24 23:11:47 vps178028 python3[934]:   File "/home/turing/.local/lib/python3.6/site-packages/backoff/_sync.py", line 99, in retry
Dec 24 23:11:47 vps178028 python3[934]:     ret = target(*args, **kwargs)
Dec 24 23:11:47 vps178028 python3[934]:   File "/home/turing/lichess-bot/lichess-bot.py", line 59, in watch_control_stream
Dec 24 23:11:47 vps178028 python3[934]:     event = json.loads(line.decode('utf-8'))
Dec 24 23:11:47 vps178028 python3[934]:   File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
Dec 24 23:11:47 vps178028 python3[934]:     return _default_decoder.decode(s)
Dec 24 23:11:47 vps178028 python3[934]:   File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
Dec 24 23:11:47 vps178028 python3[934]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Dec 24 23:11:47 vps178028 python3[934]:   File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
Dec 24 23:11:47 vps178028 python3[934]:     raise JSONDecodeError("Expecting value", s, err.value) from None
Dec 24 23:11:47 vps178028 python3[934]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)```

**Comment by gbtami** [comment]
Same here :(

**Comment by ddugovic** [comment]
I'd set up my Linux service to restart every day, except that mid-game restarts cause resignation.  But I might end up doing that anyway.

**Comment by MarkZH** [comment]
Is this still an issue?

**Comment by MarkZH** [comment]
Please reopen if this problem happens again.
