### ISSUE TITLE
lichess-bot api exception -  invalid literal 

### ISSUE THREAD

**Issue by QueensGambit** [ShailChoksi/lichess-bot#183]
Hello,
[@CrazyAra](https://lichess.org/@/CrazyAra) experienced a crash on **2019-08-21 07:37:08** due to an exception in the lichess-python API client.

The crash occured in this game:
* https://lichess.org/Aex2nuX6/black#44

In the following you can find the python log where the crash happened
```
/home/queensgambit/anaconda3/bin/python /media/queensgambit/Volume/Deep_Learning/projects/master_lichess_bot/lichess-bot/lichess-bot.py
2019-08-21 03:41:24 __main__[754] INFO 
    .   _/|
    .  // o\
    .  || ._)  lichess-bot 1.1.0
    .  //__\
    .  )___(   Play on Lichess with a bot
    
2019-08-21 03:41:24 __main__[754] INFO Welcome CrazyAra!
2019-08-21 03:41:24 __main__[754] INFO You're now connected to https://lichess.org/ and awaiting challenges.
[...]
2019-08-21 04:41:47 __main__[754] INFO     Accept Crazyhouse casual challenge from catask(2663)
2019-08-21 04:41:47 __main__[754] INFO --- Process Queue. Total Queued: 1. Total Used: 0
2019-08-21 04:41:47 __main__[754] INFO --- Process Used. Total Queued: 0. Total Used: 1
[04:41:47] /media/queensgambit/Volume/Deep_Learning/libraries/mxnet/src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.4.1. Attempting to upgrade...
[04:41:47] /media/queensgambit/Volume/Deep_Learning/libraries/mxnet/src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
[04:41:48] /media/queensgambit/Volume/Deep_Learning/libraries/mxnet/src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.4.1. Attempting to upgrade...
[04:41:48] /media/queensgambit/Volume/Deep_Learning/libraries/mxnet/src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
[04:41:48] /media/queensgambit/Volume/Deep_Learning/libraries/mxnet/src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.4.1. Attempting to upgrade...
[04:41:48] /media/queensgambit/Volume/Deep_Learning/libraries/mxnet/src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
2019-08-21 04:41:48 __main__[782] INFO +++ https://lichess.org/gQsf24Dq/black Crazyhouse vs catask(2663)
*** https://lichess.org/gQsf24Dq/black [player] catask: b'hard'
*** https://lichess.org/gQsf24Dq/black [player] catask: b'ooh new move'
*** https://lichess.org/gQsf24Dq/black [spectator] ijh: b"I wonder id=f there's any way to flag crazyara"
*** https://lichess.org/gQsf24Dq/black [spectator] ijh: b'@c3 very nice'
*** https://lichess.org/gQsf24Dq/black [spectator] NAMAB: b'nah, it has a 100ms move_overhead'
*** https://lichess.org/gQsf24Dq/black [spectator] NAMAB: b'!eval'
*** https://lichess.org/gQsf24Dq/black [spectator] CrazyAra: b'depth: 30, nps: 3347, nodes: 73537, score: {1: Score(cp=222, mate=None)}'
2019-08-21 04:46:21 __main__[782] INFO --- https://lichess.org/gQsf24Dq/black Game over
2019-08-21 04:46:21 __main__[754] INFO +++ Process Free. Total Queued: 0. Total Used: 0
2019-08-21 04:47:57 __main__[754] INFO     Accept Crazyhouse casual challenge from catask(2663)
2019-08-21 04:47:57 __main__[754] INFO --- Process Queue. Total Queued: 1. Total Used: 0
2019-08-21 04:47:57 __main__[754] INFO --- Process Used. Total Queued: 0. Total Used: 1
[04:47:57] /media/queensgambit/Volume/Deep_Learning/libraries/mxnet/src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.4.1. Attempting to upgrade...
[04:47:57] /media/queensgambit/Volume/Deep_Learning/libraries/mxnet/src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
[04:47:58] /media/queensgambit/Volume/Deep_Learning/libraries/mxnet/src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.4.1. Attempting to upgrade...
[04:47:58] /media/queensgambit/Volume/Deep_Learning/libraries/mxnet/src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
[04:47:58] /media/queensgambit/Volume/Deep_Learning/libraries/mxnet/src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.4.1. Attempting to upgrade...
[04:47:58] /media/queensgambit/Volume/Deep_Learning/libraries/mxnet/src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
2019-08-21 04:47:59 __main__[781] INFO +++ https://lichess.org/Aex2nuX6/black Crazyhouse vs catask(2663)
*** https://lichess.org/Aex2nuX6/black [player] catask: b'hard theory'
*** https://lichess.org/Aex2nuX6/black [spectator] NAMAB: b'!eval'
*** https://lichess.org/Aex2nuX6/black [spectator] CrazyAra: b'depth: 31, nps: 3242, nodes: 32074, score: {1: Score(cp=306, mate=None)}'
*** https://lichess.org/Aex2nuX6/black [spectator] NAMAB: b'I test CA so much vs SF that I forget how good it is XD'
2019-08-21 04:55:57 __main__[781] INFO --- https://lichess.org/Aex2nuX6/black Game over
2019-08-21 04:55:57 __main__[754] INFO +++ Process Free. Total Queued: 0. Total Used: 0
2019-08-21 07:37:08 __main__[779] ERROR Terminating client due to connection error
Traceback (most recent call last):
  File "/home/queensgambit/anaconda3/lib/python3.6/site-packages/urllib3/response.py", line 543, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/queensgambit/anaconda3/lib/python3.6/site-packages/urllib3/response.py", line 302, in _error_catcher
    yield
  File "/home/queensgambit/anaconda3/lib/python3.6/site-packages/urllib3/response.py", line 598, in read_chunked
    self._update_chunk_length()
  File "/home/queensgambit/anaconda3/lib/python3.6/site-packages/urllib3/response.py", line 547, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/queensgambit/anaconda3/lib/python3.6/site-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/queensgambit/anaconda3/lib/python3.6/site-packages/urllib3/response.py", line 432, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/queensgambit/anaconda3/lib/python3.6/site-packages/urllib3/response.py", line 626, in read_chunked
    self._original_response.close()
  File "/home/queensgambit/anaconda3/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/queensgambit/anaconda3/lib/python3.6/site-packages/urllib3/response.py", line 320, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/queensgambit/Volume/Deep_Learning/projects/master_lichess_bot/lichess-bot/lichess-bot.py", line 46, in watch_control_stream
    for line in response.iter_lines():
  File "/home/queensgambit/anaconda3/lib/python3.6/site-packages/requests/models.py", line 794, in iter_lines
    for chunk in self.iter_content(chunk_size=chunk_size, decode_unicode=decode_unicode):
  File "/home/queensgambit/anaconda3/lib/python3.6/site-packages/requests/models.py", line 753, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
2019-08-21 07:37:08 backoff[779] INFO Backing off watch_control_stream(...) for 0.2s (SystemExit)
2019-08-21 07:37:09 backoff[779] ERROR Giving up watch_control_stream(...) after 2 tries (json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0))
Process Process-2:
Traceback (most recent call last):
  File "/home/queensgambit/anaconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/queensgambit/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/queensgambit/anaconda3/lib/python3.6/site-packages/backoff/_sync.py", line 99, in retry
    ret = target(*args, **kwargs)
  File "/media/queensgambit/Volume/Deep_Learning/projects/master_lichess_bot/lichess-bot/lichess-bot.py", line 48, in watch_control_stream
    event = json.loads(line.decode('utf-8'))
  File "/home/queensgambit/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/queensgambit/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/queensgambit/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

and this has been the last communication of the engine over std-out which looks normal:
```
>> position fen rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR[] w KQkq - 0 1 moves e2e4 d7d5 e4d5 g8f6 f1b5 c7c6 d5c6 b7c6 b5e2 e7e5 b1c3 f8c5 P@g5 f6d5 c3d5 c6d5 d2d4 c5d4 N@h5 h8g8 P@f6 N@f5 h5g7 f5g7 f6g7 P@e7 c2c3 d4b6 g1f3 P@h3 e2b5 c8d7 d1d5 d7b5 d5b5 B@c6 B@a4 b6f2 e1f2
<< info string apply move to tree
<< info string position rn1qk1r1/p3ppPp/2b5/1Q2p1P1/B7/2P2N1p/PP3KPP/R1B4R[BNPPnp] b q - 0 20
>> go wtime 151730 btime 209770 winc 5000 binc 5000
<< info string delete unused subtrees
<< info string delete unused subtrees
<< info string reuse the tree with 79445 nodes
<< info string apply dirichlet
<< info string movetime 8119
<< info score cp 305 depth 29 nodes 110876 time 8181 nps 3842 pv N@e4 f2e3 c6b5 a4b5 P@c6 B@c4 g8g7 B@d5 Q@f2 e3e4 P@f5 e4f5 e7e6 f5g4 h7h5 g4h5 e6d5 h5h6 g7g6 h6h7 f2f3 P@e7 d8e7 g2f3 f7f6 h7g6 e7f7 g6f5 B@e6
<< rn1qk1r1/p3ppPp/2b5/1Q2p1P1/B7/2P2N1p/PP3KPP/R1B4R[BNPPnp] b q - 0 20
<< bestmove N@e4
<< info string apply move to tree
>> position fen rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR[] w KQkq - 0 1 moves e2e4 d7d5 e4d5 g8f6 f1b5 c7c6 d5c6 b7c6 b5e2 e7e5 b1c3 f8c5 P@g5 f6d5 c3d5 c6d5 d2d4 c5d4 N@h5 h8g8 P@f6 N@f5 h5g7 f5g7 f6g7 P@e7 c2c3 d4b6 g1f3 P@h3 e2b5 c8d7 d1d5 d7b5 d5b5 B@c6 B@a4 b6f2 e1f2 N@e4 f2e2
<< info string apply move to tree
<< info string position rn1qk1r1/p3ppPp/2b5/1Q2p1P1/B3n3/2P2N1p/PP2K1PP/R1B4R[BNPPp] b q - 2 21
>> go wtime 147210 btime 206310 winc 5000 binc 5000
<< info string delete unused subtrees
<< info string delete unused subtrees
<< info string reuse the tree with 869 nodes
<< info string apply dirichlet
<< info string movetime 8679
<< info score cp 715 depth 34 nodes 38319 time 8864 nps 4225 pv c6b5 a4b5 P@c6 c1e3 c6b5 B@b1 h3g2 b1e4 B@c4 e2f2 Q@e2 f2g3 g2h1q a1h1 e2e3 B@c6 b8c6 e4c6 B@d7 N@f6 e7f6 N@d6 e8e7 N@f5 d7f5 d6f5 e7e6 f5e3 P@f4 g3g2 f4e3 P@f5 e6d6 a2a3
<< rn1qk1r1/p3ppPp/2b5/1Q2p1P1/B3n3/2P2N1p/PP2K1PP/R1B4R[BNPPp] b q - 2 21
<< bestmove c6b5
<< info string apply move to tree
>> position fen rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR[] w KQkq - 0 1 moves e2e4 d7d5 e4d5 g8f6 f1b5 c7c6 d5c6 b7c6 b5e2 e7e5 b1c3 f8c5 P@g5 f6d5 c3d5 c6d5 d2d4 c5d4 N@h5 h8g8 P@f6 N@f5 h5g7 f5g7 f6g7 P@e7 c2c3 d4b6 g1f3 P@h3 e2b5 c8d7 d1d5 d7b5 d5b5 B@c6 B@a4 b6f2 e1f2 N@e4 f2e2 c6b5 a4b5
<< info string apply move to tree
<< info string position rn1qk1r1/p3ppPp/8/1B2p1P1/4n3/2P2N1p/PP2K1PP/R1B4R[BBNPPqp] b q - 0 22
>> go wtime 152210 btime 202220 winc 5000 binc 5000
<< info string delete unused subtrees
<< info string delete unused subtrees
<< info string reuse the tree with 37855 nodes
<< info string apply dirichlet
<< info string movetime 10042
<< info score cp 771 depth 17 nodes 81055 time 10048 nps 4299 pv P@c6 c1e3 c6b5 B@b1 h3g2 b1e4 B@d3 e4d3 d8d3 e2d3 B@c4 d3d2 Q@e2 d2c1 g2h1q B@g1 R@d1
<< rn1qk1r1/p3ppPp/8/1B2p1P1/4n3/2P2N1p/PP2K1PP/R1B4R[BBNPPqp] b q - 0 22
<< bestmove P@c6
<< info string apply move to tree
>> quit
```

It seems to me that there was a problem when interpreting the chat messages specifically the characters `17. p@e6 ` from chat, but I might be wrong about this.

My local repository state of the lichess-bot api was unfortunately still at commit a4799241d3b4b4168c93ff4277428796381aebcf, Mon Dec 10 15:03:02 2018 +0100, so the problem might have already been fixed.

I will update to current master now.

**Comment by gbtami** [comment]
I think this has nothing to do with chat messages. This is related to error handling of watch_control_stream() instead. I myself use @noobpwnftw solution in my https://github.com/gbtami/lichess-bot-variants fork. It works. See https://github.com/noobpwnftw/lichess-bot/blob/master/lichess-bot.py#L54

**Comment by QueensGambit** [comment]
Thanks for you for fast reply @gbtami. Nice that you could track down the cause for this problem.

**Comment by ShailChoksi** [comment]
I merged in noobpwnftw PR changes recently. Is this still an issue?

**Comment by QueensGambit** [comment]
@ShailChoksi: I haven't tested it since then. This error was hard to reproduce because it crashed seemingly randomly after an uptime of about 17.5 hours.
What might have facilitated the problem is that different people chatted at the same time.

**Comment by MarkZH** [comment]
Please reopen if this crash occurs again.
