### ISSUE TITLE
KeyError: 'type'

### ISSUE THREAD

**Issue by SeanTolstoyevski** [ShailChoksi/lichess-bot#188]
```
D:\d\github\lichess-bot>v35 venv
Using base prefix 'c:\\coding\\main\\py3.7.5-64'
  No LICENSE.txt / LICENSE found in source
New python executable in D:\d\github\lichess-bot\venv\Scripts\py35.exe
Also creating executable in D:\d\github\lichess-bot\venv\Scripts\python.exe
Installing setuptools, pip, wheel...
done.

D:\d\github\lichess-bot>venv\Scripts\activate

(venv) D:\d\github\lichess-bot>pip install -r requirements.txt
Collecting certifi==2018.11.29
  Downloading https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl (154kB)
     |████████████████████████████████| 163kB 32kB/s
Collecting chardet==3.0.4
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna==2.8
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting python-chess==0.24.1
  Downloading https://files.pythonhosted.org/packages/98/22/799748b661e2dfe6b64cfa02f366990d347c31e56d3b546802dd1a22aac2/python-chess-0.24.1.tar.gz (141kB)
     |████████████████████████████████| 143kB 47kB/s
Collecting PyYAML>=4.2b1
  Using cached https://files.pythonhosted.org/packages/9e/9c/d4865f9b24c7cfe83181e892ec5ade1435cde46bc606bb5ac2b297d75c38/PyYAML-5.3-cp37-cp37m-win_amd64.whl
Collecting requests>=2.21.0
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting urllib3==1.24.2
  Downloading https://files.pythonhosted.org/packages/df/1c/59cca3abf96f991f2ec3131a4ffe72ae3d9ea1f5894abe8a9c5e3c77cfee/urllib3-1.24.2-py2.py3-none-any.whl (131kB)
     |████████████████████████████████| 133kB 67kB/s
Collecting backoff==1.7.1
  Downloading https://files.pythonhosted.org/packages/97/c2/96953dbfea5b46370edfcacb2ec2e02463061e9aff7370d0978bc25013ba/backoff-1.7.1-py2.py3-none-any.whl (42kB)
     |████████████████████████████████| 51kB 76kB/s
Building wheels for collected packages: python-chess
  Building wheel for python-chess (setup.py) ... done
  Created wheel for python-chess: filename=python_chess-0.24.1-cp37-none-any.whl size=126505 sha256=3a65b86b10d3151dec0cfd950bf6b3704a1d3d4103762d331859a1e74a2ee28c
  Stored in directory: C:\Users\DawnLight\AppData\Local\pip\Cache\wheels\40\ce\66\30b2b779917f5b3c70d086dda8aacc5a13c2011d01f60ad338
Successfully built python-chess
Installing collected packages: certifi, chardet, idna, python-chess, PyYAML, urllib3, requests, backoff
Successfully installed PyYAML-5.3 backoff-1.7.1 certifi-2018.11.29 chardet-3.0.4 idna-2.8 python-chess-0.24.1 requests-2.22.0 urllib3-1.24.2

(venv) D:\d\github\lichess-bot>python lichess-bot.py
2020-01-16 07:31:10,755:
    .   _/|
    .  // o\
    .  || ._)  lichess-bot 1.1.4
    .  //__\
    .  )___(   Play on Lichess with a bot

D:\d\github\lichess-bot\config.py:8: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  CONFIG = yaml.load(stream)
2020-01-16 07:31:11,063: Welcome ararimbelami!
2020-01-16 07:31:11,063: You're now connected to https://lichess.org/ and awaiting challenges.
Traceback (most recent call last):
  File "lichess-bot.py", line 309, in <module>
    start(li, user_profile, engine_factory, CONFIG)
  File "lichess-bot.py", line 83, in start
    if event["type"] == "terminated":
KeyError: 'type'

(venv) D:\d\github\lichess-bot>python lichess-bot.py
2020-01-16 07:31:56,079:
    .   _/|
    .  // o\
    .  || ._)  lichess-bot 1.1.4
    .  //__\
    .  )___(   Play on Lichess with a bot

D:\d\github\lichess-bot\config.py:8: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  CONFIG = yaml.load(stream)
2020-01-16 07:31:56,382: Welcome ararimbelami!
2020-01-16 07:31:56,382: You're now connected to https://lichess.org/ and awaiting challenges.
Traceback (most recent call last):
  File "lichess-bot.py", line 309, in <module>
    start(li, user_profile, engine_factory, CONFIG)
  File "lichess-bot.py", line 83, in start
    if event["type"] == "terminated":
KeyError: 'type'

(venv) D:\d\github\lichess-bot>python lichess.py

(venv) D:\d\github\lichess-bot>python lichess-bot.py -u
2020-01-16 07:32:51,975:
    .   _/|
    .  // o\
    .  || ._)  lichess-bot 1.1.4
    .  //__\
    .  )___(   Play on Lichess with a bot

D:\d\github\lichess-bot\config.py:8: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  CONFIG = yaml.load(stream)
2020-01-16 07:32:52,667: Welcome ararimbelami!
2020-01-16 07:32:52,675: You're now connected to https://lichess.org/ and awaiting challenges.
Traceback (most recent call last):
  File "lichess-bot.py", line 309, in <module>
    start(li, user_profile, engine_factory, CONFIG)
  File "lichess-bot.py", line 83, in start
    if event["type"] == "terminated":
KeyError: 'type'

(venv) D:\d\github\lichess-bot>python lichess-bot.py
2020-01-16 07:40:35,814:
    .   _/|
    .  // o\
    .  || ._)  lichess-bot 1.1.4
    .  //__\
    .  )___(   Play on Lichess with a bot

D:\d\github\lichess-bot\config.py:8: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  CONFIG = yaml.load(stream)
2020-01-16 07:40:36,184: Welcome ararimbelami!
2020-01-16 07:40:36,184: You're now connected to https://lichess.org/ and awaiting challenges.
Traceback (most recent call last):
  File "lichess-bot.py", line 309, in <module>
    start(li, user_profile, engine_factory, CONFIG)
  File "lichess-bot.py", line 83, in start
    if event["type"] == "terminated":
KeyError: 'type'

(venv) D:\d\github\lichess-bot>python lichess-bot.py
2020-01-16 07:42:38,956:
    .   _/|
    .  // o\
    .  || ._)  lichess-bot 1.1.4
    .  //__\
    .  )___(   Play on Lichess with a bot

D:\d\github\lichess-bot\config.py:8: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  CONFIG = yaml.load(stream)
2020-01-16 07:42:39,276: Welcome ararimbelami!
2020-01-16 07:42:39,276: You're now connected to https://lichess.org/ and awaiting challenges.
Traceback (most recent call last):
  File "lichess-bot.py", line 309, in <module>
    start(li, user_profile, engine_factory, CONFIG)
  File "lichess-bot.py", line 83, in start
    if event["type"] == "terminated":
KeyError: 'type'

(venv) D:\d\github\lichess-bot>

```

**Comment by vasilykuzmin** [comment]
How did you solve this error?
