### ISSUE TITLE
Error getting variant

### ISSUE THREAD

**Issue by thomasahle** [ShailChoksi/lichess-bot#194]
Both of my bots are currently getting the following error:

```
2020-02-27 11:44:24,901: Backing off play_game(...) for 0.1s (TypeError: 'NoneType' object is not subscriptable)
2020-02-27 11:44:28,899: Backing off play_game(...) for 0.8s (TypeError: 'NoneType' object is not subscriptable)
2020-02-27 11:44:32,899: Backing off play_game(...) for 3.9s (TypeError: 'NoneType' object is not subscriptable)
2020-02-27 11:44:36,904: Backing off play_game(...) for 0.8s (TypeError: 'NoneType' object is not subscriptable)
2020-02-27 11:44:40,902: Backing off play_game(...) for 0.7s (TypeError: 'NoneType' object is not subscriptable)
2020-02-27 11:44:44,904: Backing off play_game(...) for 5.3s (TypeError: 'NoneType' object is not subscriptable)
2020-02-27 11:44:50,298: Backing off play_game(...) for 22.7s (TypeError: 'NoneType' object is not subscriptable)
2020-02-27 11:45:13,088: Backing off play_game(...) for 35.8s (TypeError: 'NoneType' object is not subscriptable)
2020-02-27 11:45:49,016: Backing off play_game(...) for 63.6s (TypeError: 'NoneType' object is not subscriptable)
2020-02-27 11:46:52,751: Backing off play_game(...) for 141.9s (TypeError: 'NoneType' object is not subscriptable)
2020-02-27 11:49:14,819: Backing off play_game(...) for 157.6s (TypeError: 'NoneType' object is not subscriptable)
2020-02-27 11:51:52,674: Backing off play_game(...) for 152.2s (TypeError: 'NoneType' object is not subscriptable)
2020-02-27 11:54:25,147: Giving up play_game(...) after 13 tries (TypeError: 'NoneType' object is not subscriptable)
Traceback (most recent call last):
  File "/home/thdy/lichess-bot/logging_pool.py", line 16, in __call__
    result = self.__callable(*args, **kwargs)
  File "/home/thdy/lichess-bot/.venv/lib/python3.5/site-packages/backoff/_sync.py", line 99, in retry
    ret = target(*args, **kwargs)
  File "lichess-bot.py", line 136, in play_game
    game = model.Game(initial_state, user_profile["username"], li.baseUrl, config.get("abort_time", 20))
  File "/home/thdy/lichess-bot/model.py", line 68, in __init__
    self.variant_name = json.get("variant")["name"]
TypeError: 'NoneType' object is not subscriptable
```

It looks like lichess-bot is assuming a variant attribute that it is not getting from the server?

**Comment by codeandkey** [comment]
Having the same issue with my bot. Some part of the lichess API seems to have changed, as the error began appearing without any updates to lichess-bot.

**Comment by ShailChoksi** [comment]
I can take a look at this later tonight

**Comment by ornicar** [comment]
https://lichess.org/forum/lichess-feedback/lichess-bots-broken-today
