### ISSUE TITLE
KeyError: 'type'

### ISSUE THREAD

**Issue by harirakul** [ShailChoksi/lichess-bot#197]
getting this error whenever starting the bot

Traceback (most recent call last):
  File "lichess-bot.py", line 426, in <module>
    start(li, user_profile, engine_factory, CONFIG)
  File "lichess-bot.py", line 83, in start
    if event["type"] == "terminated":
KeyError: 'type'

**Comment by vasilykuzmin** [comment]
How did you solve this error?
