### ISSUE TITLE
xboard engine still at starting position after book ends

### ISSUE THREAD

**Issue by zenpawn** [ShailChoksi/lichess-bot#206]
It seems the script tells lichess about the book move but not the engine (at least when the protocol is set to xboard).

The engine was playing black here, and white's last move was c4b3.  The book line has ended, and you can see the board is still at the starting position.

```
(.venv) PS C:\chess-engine-dev\lichess-bot> python lichess-bot.py -v
2020-05-30 16:24:54,718:
    .   _/|
    .  // o\
    .  || ._)  lichess-bot 1.1.4
    .  //__\
    .  )___(   Play on Lichess with a bot

2020-05-30 16:24:54,750: Starting new HTTPS connection (1): lichess.org:443
2020-05-30 16:24:55,173: https://lichess.org:443 "GET /api/account HTTP/1.1" 200 None
2020-05-30 16:24:55,173: Welcome RookieMonsterC!
2020-05-30 16:24:55,188: You're now connected to https://lichess.org/ and awaiting challenges.
2020-05-30 16:25:27,789:     Accept Bullet casual challenge from zenpawn(1500)
2020-05-30 16:25:27,789: Resetting dropped connection: lichess.org
2020-05-30 16:25:28,523: https://lichess.org:443 "POST /api/challenge/Qd5GtpRm/accept HTTP/1.1" 200 11
2020-05-30 16:25:28,523: --- Process Queue. Total Queued: 1. Total Used: 0
2020-05-30 16:25:28,523: --- Process Used. Total Queued: 0. Total Used: 1
exception parsing pv
Traceback (most recent call last):
  File "C:\chess-engine-dev\lichess-bot\.venv\lib\site-packages\chess\xboard.py", line 43, in try_move
    move = board.push_uci(move)
  File "C:\chess-engine-dev\lichess-bot\.venv\lib\site-packages\chess\__init__.py", line 2751, in push_uci
    move = self.parse_uci(uci)
  File "C:\chess-engine-dev\lichess-bot\.venv\lib\site-packages\chess\__init__.py", line 2738, in parse_uci
    raise ValueError("illegal uci: {} in {}".format(repr(uci), self.fen()))
ValueError: illegal uci: 'c4b3' in rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\chess-engine-dev\lichess-bot\.venv\lib\site-packages\chess\xboard.py", line 46, in try_move
    move = board.push_san(move)
  File "C:\chess-engine-dev\lichess-bot\.venv\lib\site-packages\chess\__init__.py", line 2700, in push_san
    move = self.parse_san(san)
  File "C:\chess-engine-dev\lichess-bot\.venv\lib\site-packages\chess\__init__.py", line 2687, in parse_san
    raise ValueError("illegal san: {} in {}".format(repr(san), self.fen()))
ValueError: illegal san: 'c4b3' in rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
```

**Comment by MarkZH** [comment]
Does this issue still occur?

**Comment by MarkZH** [comment]
Please reopen if the problem occurs again.
