### ISSUE TITLE
"exception parsing bestmove" from ponder

### ISSUE THREAD

**Issue by aurimus** [ShailChoksi/lichess-bot#209]
I'm getting these errors with `ValueError: illegal uci` .. after ponder. I have tried different Leela versions with different networks and while the frequency of the errors does change - they are always present (that's why I think it's lichess bot). 

**update:** after turning ponder off, no more errors.. still would be nice if ponder would work ..

I'm using v0.26.0-rc1 Leela

![image](https://user-images.githubusercontent.com/1052992/86237617-ca393980-bba4-11ea-8b4f-9faa121c5818.png)

Thank You for great work on lichess!

**Comment by cosinekitty** [comment]
I may have run into a similar error. It caused my engine to lose on time.

```
***** https://lichess.org/EjBVDVJY/white [spectator] lichess: b'Black offers draw'
2020-11-11 01:56:37,186: Searching for wtime 419880 btime 357220
    depth: 7
    nodes: 2315146
    score: -525
2020-11-11 01:56:42,408: Giving up api_post(...) after 1 tries (requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://lichess.org/api/bot/game/EjBVDVJY/move/h8g7)
*** https://lichess.org/EjBVDVJY/white [player] lichess: b'Black offers draw'
*** https://lichess.org/EjBVDVJY/white [spectator] lichess: b'White declines draw'
*** https://lichess.org/EjBVDVJY/white [player] lichess: b'White declines draw'
2020-11-11 01:56:55,285: Searching for wtime 416800 btime 339350
2020-11-11 01:56:55,286: exception parsing pv
Traceback (most recent call last):
  File "/home/don/github/lichess-bot/.venv/lib/python3.5/site-packages/chess/xboard.py", line 43, in try_move
    move = board.push_uci(move)
  File "/home/don/github/lichess-bot/.venv/lib/python3.5/site-packages/chess/__init__.py", line 2751, in push_uci
    move = self.parse_uci(uci)
  File "/home/don/github/lichess-bot/.venv/lib/python3.5/site-packages/chess/__init__.py", line 2738, in parse_uci
    raise ValueError("illegal uci: {} in {}".format(repr(uci), self.fen()))
ValueError: illegal uci: 'h8g7' in r4r2/6k1/4p1p1/P7/1P6/1R6/5PPP/R5K1 w - - 3 34

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/don/github/lichess-bot/.venv/lib/python3.5/site-packages/chess/xboard.py", line 46, in try_move
    move = board.push_san(move)
  File "/home/don/github/lichess-bot/.venv/lib/python3.5/site-packages/chess/__init__.py", line 2700, in push_san
    move = self.parse_san(san)
  File "/home/don/github/lichess-bot/.venv/lib/python3.5/site-packages/chess/__init__.py", line 2687, in parse_san
    raise ValueError("illegal san: {} in {}".format(repr(san), self.fen()))
ValueError: illegal san: 'h8g7' in r4r2/6k1/4p1p1/P7/1P6/1R6/5PPP/R5K1 w - - 3 34
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/don/github/lichess-bot/.venv/lib/python3.5/site-packages/chess/engine.py", line 139, in _receiving_thread_target
    self.engine.on_line_received(line.rstrip())
  File "/home/don/github/lichess-bot/.venv/lib/python3.5/site-packages/chess/xboard.py", line 357, in on_line_received
    raise EngineStateException(exception_msg)
chess.engine.EngineStateException: Engine received an illegal move: h8g7
**
```

**Comment by amanjpro** [comment]
Same here

**Comment by MarkZH** [comment]
Both lichess-bot and the python-chess library it uses have been upgraded to correctly implement UCI pondering (#308). Please reopen if there are still problems.
