### ISSUE TITLE
Lichess bot does not work

### ISSUE THREAD

**Issue by armstrong-a** [ShailChoksi/lichess-bot#224]
I get the following error while trying to run the Lichess bot in Windows 10.
Kindly help to resolve.

There appears to be a syntax problem with your config.yml
Traceback (most recent call last):
  File "lichess-bot.py", line 421, in <module>
    CONFIG = load_config(args.config or "./config.yml")
  File "C:\Users\Armstrong\OneDrive\Desktop\lichess leela\lichess-bot-master\config.py", line 11, in load_config
    raise e
  File "C:\Users\Armstrong\OneDrive\Desktop\lichess leela\lichess-bot-master\config.py", line 8, in load_config
    CONFIG = yaml.safe_load(stream)
  File "C:\Users\Armstrong\AppData\Roaming\Python\Python38\site-packages\yaml\__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\Armstrong\AppData\Roaming\Python\Python38\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\Armstrong\AppData\Roaming\Python\Python38\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\Armstrong\AppData\Roaming\Python\Python38\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\Armstrong\AppData\Roaming\Python\Python38\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\Armstrong\AppData\Roaming\Python\Python38\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\Armstrong\AppData\Roaming\Python\Python38\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\Armstrong\AppData\Roaming\Python\Python38\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\Armstrong\AppData\Roaming\Python\Python38\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\Armstrong\AppData\Roaming\Python\Python38\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\Armstrong\AppData\Roaming\Python\Python38\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\Armstrong\AppData\Roaming\Python\Python38\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\Armstrong\AppData\Roaming\Python\Python38\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\Armstrong\AppData\Roaming\Python\Python38\site-packages\yaml\composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "C:\Users\Armstrong\AppData\Roaming\Python\Python38\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\Armstrong\AppData\Roaming\Python\Python38\site-packages\yaml\parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "C:\Users\Armstrong\AppData\Roaming\Python\Python38\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "C:\Users\Armstrong\AppData\Roaming\Python\Python38\site-packages\yaml\scanner.py", line 251, in fetch_more_tokens
    return self.fetch_double()
  File "C:\Users\Armstrong\AppData\Roaming\Python\Python38\site-packages\yaml\scanner.py", line 655, in fetch_double
    self.fetch_flow_scalar(style='"')
  File "C:\Users\Armstrong\AppData\Roaming\Python\Python38\site-packages\yaml\scanner.py", line 666, in fetch_flow_scalar
    self.tokens.append(self.scan_flow_scalar(style))
  File "C:\Users\Armstrong\AppData\Roaming\Python\Python38\site-packages\yaml\scanner.py", line 1149, in scan_flow_scalar
    chunks.extend(self.scan_flow_scalar_non_spaces(double, start_mark))
  File "C:\Users\Armstrong\AppData\Roaming\Python\Python38\site-packages\yaml\scanner.py", line 1213, in scan_flow_scalar_non_spaces
    raise ScannerError("while scanning a double-quoted scalar", start_mark,
yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "./config.yml", line 41, column 15
expected escape sequence of 8 hexdecimal numbers, but found 's'
  in "./config.yml", line 41, column 20

**Comment by sander-NULL** [comment]
Could you provide your config.yml (**but remove your OAuth first**)? Did you maybe accidentally use tabs instead of white spaces somewhere in the file? Also I think I recall a problem when the #'s at the end of the line just before the comments were not aligned anymore.

**Comment by armstrong-a** [comment]
Thanks for your support.
Have attached the file.
[config.yml.txt](https://github.com/ShailChoksi/lichess-bot/files/5321596/config.yml.txt)

**Comment by sander-NULL** [comment]
Great, did you check for issues that I have stated above?

**Comment by armstrong-a** [comment]
I have checked. Could not find any errors.
Meanwhile, copied a config file from this website dated 15h Aug.
Now works normally.
This concern is intermittent.
Will update you if the concern recurs.
Thanks!

**Comment by IbaiBuR** [comment]
I also get this error while usign lichess-bot 1.1.5 
Traceback (most recent call last):
  File "lichess-bot.py", line 434, in <module>
    start(li, user_profile, engine_factory, CONFIG)
  File "lichess-bot.py", line 83, in start
    if event["type"] == "terminated":
KeyError: 'type'

**Comment by armstrong-a** [comment]
Lichess bot was running overnight.
In morning, while stared again, get the same error.
[New Text Document (4).txt](https://github.com/ShailChoksi/lichess-bot/files/5324812/New.Text.Document.4.txt)

**Comment by MarkZH** [comment]
In case this is still a problem, I think you either need to switch backslashes `\` with forward slashes `/` in that syzygy line. Doubling up the backslashes `\\` could also work.
