### ISSUE TITLE
Can't get bot profile

### ISSUE THREAD

**Issue by chessBOTneeder** [ShailChoksi/lichess-bot#252]
the code can't get bot profile
   .   _/|
    .  // o\
    .  || ._)  lichess-bot 1.1.4
    .  //__\
    .  )___(   Play on Lichess with a bot
    
2021-01-29 11:34:09,839: Giving up api_get(...) after 1 tries (requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://lichess.org/api/account)
Traceback (most recent call last):
  File "lichess-bot.py", line 426, in <module>
    user_profile = li.get_profile()
  File "/Users/shujuan/Documents/lichess-bot-4/lichess.py", line 98, in get_profile
    profile = self.api_get(ENDPOINTS["profile"])
  File "/Users/shujuan/Documents/lichess-bot-4/.venv/lib/python3.8/site-packages/backoff/_sync.py", line 99, in retry
    ret = target(*args, **kwargs)
  File "/Users/shujuan/Documents/lichess-bot-4/lichess.py", line 53, in api_get
    response.raise_for_status()
  File "/Users/shujuan/Documents/lichess-bot-4/.venv/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://lichess.org/api/account

**Comment by TheYoBots** [comment]
Check whether your API Access token is correct. Also make sure no games are played in the account that you want to upgrade to a bot.

**Comment by MarkZH** [comment]
@chessBOTneeder Were you able to get your bot working?

**Comment by MarkZH** [comment]
Please reopen this issue if you are still having problems.
