### ISSUE TITLE
Command prompt

### ISSUE THREAD

**Issue by TG-KRISH** [ShailChoksi/lichess-bot#360]
It shows alike this
2021-06-26 20:50:22,127:
    .   _/|
    .  // o\
    .  || ._)  lichess-bot 1.2.0
    .  //__\
    .  )___(   Play on Lichess with a bot

There appears to be a syntax problem with your config.yml
Traceback (most recent call last):
  File "lichess-bot.py", line 339, in <module>
    CONFIG = load_config(args.config or "./config.yml")
  File "C:\Lichess\Higher-end-bot-main\config.py", line 12, in load_config
    raise e
  File "C:\Lichess\Higher-end-bot-main\config.py", line 9, in load_config
    CONFIG = yaml.safe_load(stream)
  File "C:\Lichess\Higher-end-bot-main\.venv\lib\site-packages\yaml\__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "C:\Lichess\Higher-end-bot-main\.venv\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Lichess\Higher-end-bot-main\.venv\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Lichess\Higher-end-bot-main\.venv\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Lichess\Higher-end-bot-main\.venv\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Lichess\Higher-end-bot-main\.venv\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Lichess\Higher-end-bot-main\.venv\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Lichess\Higher-end-bot-main\.venv\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Lichess\Higher-end-bot-main\.venv\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "C:\Lichess\Higher-end-bot-main\.venv\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Lichess\Higher-end-bot-main\.venv\lib\site-packages\yaml\parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "./config.yml", line 49, column 3
expected <block end>, but found '<block sequence start>'
  in "./config.yml", line 73, column 4

**Comment by TG-KRISH** [comment]
**Can someone help me**

**Comment by TG-KRISH** [comment]
pls

**Comment by TG-KRISH** [comment]
What shall I do??

**Comment by icecream17** [comment]
The error means "Uh oh. There's a random (quotation mark `"`) somewhere that shouldn't exist."
