### ISSUE TITLE
what this error

### ISSUE THREAD

**Issue by barca-cloud** [ShailChoksi/lichess-bot#384]
Traceback (most recent call last):
  File "C:\Users\Tubu\Desktop\NeverUnderistimateMe\lichess-bot-master\lichess-bot.py", line 440, in <module>
    CONFIG = load_config(args.config or "./config.yml")
  File "C:\Users\Tubu\Desktop\NeverUnderistimateMe\lichess-bot-master\config.py", line 45, in load_config
    raise Exception("The engine %s file does not exist." % engine)
Exception: The engine ./engines/stcokfish.exe file does not exist.

(.venv) C:\Users\Tubu\Desktop\NeverUnderistimateMe\lichess-bot-master> what is thios ??

**Comment by MarkZH** [comment]
It looks like a misspelling of `stockfish.exe` in the config file. This Exception line shows that the config file has `stcokfish.exe`.

**Comment by barca-cloud** [comment]
oh noo i got everything right but for my silly mistake .
