### ISSUE TITLE
help error

### ISSUE THREAD

**Issue by thechipsss** [ShailChoksi/lichess-bot#492]
i am getting after i upgrade it 
  ERROR    There appears to be a syntax problem with your config.yml                     config.py:14
Traceback (most recent call last):
  File "C:\Users\Tubu\Desktop\Thefinalbossbot\lichess-bot-master\lichess-bot.py", line 774, in <module>
    CONFIG = load_config(args.config or "./config.yml")
  File "C:\Users\Tubu\Desktop\Thefinalbossbot\lichess-bot-master\config.py", line 15, in load_config
    raise e
  File "C:\Users\Tubu\Desktop\Thefinalbossbot\lichess-bot-master\config.py", line 12, in load_config
    CONFIG = yaml.safe_load(stream)
  File "C:\Users\Tubu\Desktop\Thefinalbossbot\lichess-bot-master\.venv\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\Tubu\Desktop\Thefinalbossbot\lichess-bot-master\.venv\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\Tubu\Desktop\Thefinalbossbot\lichess-bot-master\.venv\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\Tubu\Desktop\Thefinalbossbot\lichess-bot-master\.venv\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\Tubu\Desktop\Thefinalbossbot\lichess-bot-master\.venv\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\Tubu\Desktop\Thefinalbossbot\lichess-bot-master\.venv\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\Tubu\Desktop\Thefinalbossbot\lichess-bot-master\.venv\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\Tubu\Desktop\Thefinalbossbot\lichess-bot-master\.venv\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\Tubu\Desktop\Thefinalbossbot\lichess-bot-master\.venv\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\Tubu\Desktop\Thefinalbossbot\lichess-bot-master\.venv\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\Tubu\Desktop\Thefinalbossbot\lichess-bot-master\.venv\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "C:\Users\Tubu\Desktop\Thefinalbossbot\lichess-bot-master\.venv\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\Tubu\Desktop\Thefinalbossbot\lichess-bot-master\.venv\lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "C:\Users\Tubu\Desktop\Thefinalbossbot\lichess-bot-master\.venv\lib\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "C:\Users\Tubu\Desktop\Thefinalbossbot\lichess-bot-master\.venv\lib\site-packages\yaml\scanner.py", line 162, in fetch_more_tokens
    self.stale_possible_simple_keys()
  File "C:\Users\Tubu\Desktop\Thefinalbossbot\lichess-bot-master\.venv\lib\site-packages\yaml\scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "./config.yml", line 60, column 5
could not find expected ':'
  in "./config.yml", line 61, column 5

(.venv) C:\Users\Tubu\Desktop\Thefinalbossbot\lichess-bot-master>

**Comment by AttackingOrDefending** [comment]
Can you send your config.yml with the token removed?

**Comment by thechipsss** [comment]
where can i find that?

**Comment by AttackingOrDefending** [comment]
Inside your `lichess-bot` directory (`C:\Users\Tubu\Desktop\Thefinalbossbot\lichess-bot-master`) there should be a file named `config.yml`. Also, remember to remove your token before uploading the file.

**Comment by thechipsss** [comment]
token: "xxxxxxxxx"    # Lichess OAuth2 Token.
url: "https://lichess.org/"  # Lichess base URL.

engine:                      # Engine settings.
  dir: "./engines/"          # Directory containing the engine. This can be an absolute path or one relative to lichess-bot/.
  name: "stockfish.exe"        # Binary name of the engine to use.
  working_dir: ""            # Directory where the chess engine will read and write files. If blank or missing, the current directory is used.
  protocol: "uci"            # "uci" or "xboard"
  ponder: true               # Think on opponent's time.
  polyglot:
    enabled: false           # Activate polyglot book.
    book:
      standard:              # List of book file paths for variant standard.
        - engines/book1.bin
        - engines/book2.bin
#     atomic:                # List of book file paths for variant atomic.
#       - engines/atomicbook1.bin
#       - engines/atomicbook2.bin
#     etc.
#     Use the same pattern for 'giveaway' (antichess), 'crazyhouse', 'horde', 'kingofthehill', 'racingkings' and '3check' as well.
    min_weight: 1            # Does not select moves with weight below min_weight (min 0, max: 65535).
    selection: "weighted_random" # Move selection is one of "weighted_random", "uniform_random" or "best_move" (but not below the min_weight in the 2nd and 3rd case).
    max_depth: 8             # Half move max depth.
  draw_or_resign:
    resign_enabled: false
    resign_score: -1000      # If the score is less than or equal to this value, the bot resigns (in cp).
    resign_for_egtb_minus_two: true # If true the bot will resign in positions where the online_egtb returns a wdl of -2.
    resign_moves: 3          # How many moves in a row the score has to be below the resign value.
    offer_draw_enabled: false
    offer_draw_score: 0      # If the absolute value of the score is less than or equal to this value, the bot offers/accepts draw (in cp).
    offer_draw_for_egtb_zero: true # If true the bot will offer/accept draw in positions where the online_egtb returns a wdl of 0.
    offer_draw_moves: 5      # How many moves in a row the absolute value of the score has to be below the draw value.
    offer_draw_pieces: 10    # Only if the pieces on board are less than or equal to this value, the bot offers/accepts draw.
  online_moves:
    chessdb_book:
      enabled: false
      min_time: 20
      move_quality: "good"   # One of "all", "good", "best".
      min_depth: 20          # Only for move_quality: "best".
      contribute: true
    lichess_cloud_analysis:
      enabled: false
      min_time: 20
      move_quality: "good"   # One of "good", "best".
      max_score_difference: 50 # Only for move_quality: "good". The maximum score difference (in cp) between the best move and the other moves.
      min_depth: 20
      min_knodes: 0
    online_egtb:
      enabled: false
      min_time: 20
      max_pieces: 7
      source: "lichess"      # One of "lichess", "chessdb".
      move_quality: "best"   # One of "good", "best".
# engine_options:            # Any custom command line params to pass to the engine.
#   cpuct: 3.1
  homemade_options:
#   Hash: 256
  uci_options:               # Arbitrary UCI options passed to the engine.
    Move Overhead: 1000      # Increase if your bot flags games too often.
    Threads:12               # Max CPU threads the engine can use.
    Hash: 256                # Max memory (in megabytes) the engine can allocate.
#   go_commands:             # Additional options to pass to the UCI go command.
#     nodes: 1               # Search so many nodes only.
#     depth: 5               # Search depth ply only.
#     movetime: 1000         # Integer. Search exactly movetime milliseconds.
# xboard_options:            # Arbitrary XBoard options passed to the engine.
#   cores: "4"
#   memory: "4096"
#   egtpath:                 # Directory containing egtb (endgame tablabases), relative to this project. For 'xboard' engines.
#     gaviota: "Gaviota path"
#     nalimov: "Nalimov Path"
#     scorpio: "Scorpio Path"
#     syzygy: "Syzygy Path"
#   go_commands:             # Additional options to pass to the XBoard go command.
#     depth: 5               # Search depth ply only.
#     Do note that the go commands 'movetime' and 'nodes' are invalid and may cause bad time management for XBoard engines.
  silence_stderr: false      # Some engines (yes you, Leela) are very noisy.

abort_time: 20               # Time to abort a game in seconds when there is no activity.
fake_think_time: false       # Artificially slow down the bot to pretend like it's thinking.
rate_limiting_delay: 0       # Time (in ms) to delay after sending a move to prevent "Too Many Requests" errors.
move_overhead: 2000          # Increase if your bot flags games too often.

correspondence:
    move_time: 60            # Time in seconds to search in correspondence games.
    checkin_period: 600      # How often to check for opponent moves in correspondence games after disconnecting.
    disconnect_time: 300     # Time before disconnecting from a correspondence game.
    ponder: false            # Ponder in correspondence games the bot is connected to.

challenge:                   # Incoming challenges.
  concurrency: 1             # Number of games to play simultaneously.
  sort_by: "best"            # Possible values: "best" and "first".
  accept_bot: false          # Accepts challenges coming from other bots.
  only_bot: false            # Accept challenges by bots only.
  max_increment: 180         # Maximum amount of increment to accept a challenge. The max is 180. Set to 0 for no increment.
  min_increment: 0           # Minimum amount of increment to accept a challenge.
  max_base: 315360000        # Maximum amount of base time to accept a challenge. The max is 315360000 (10 years).
  min_base: 0                # Minimum amount of base time to accept a challenge.
  variants:                  # Chess variants to accept (https://lichess.org/variant).
    - standard
#   - fromPosition
#   - antichess
#   - atomic
#   - chess960
#   - crazyhouse
#   - horde
#   - kingOfTheHill
#   - racingKings
#   - threeCheck
  time_controls:             # Time controls to accept.
    - bullet
    - blitz
    - rapid
#   - classical
#   - correspondence
  modes:                     # Game modes to accept.
    - casual                 # Unrated games.
    - rated                  # Rated games - must comment if the engine doesn't try to win.

greeting:
    # Optional substitution keywords (include curly braces):
    #   {opponent} to insert opponent's name
    #   {me} to insert bot's name
    # Any other words in curly braces will be removed.
    hello: "Hi! I'm {me}. Good luck! Type !help for a list of commands I can respond to." # Message to send to chat at the start of a game
    goodbye: "Good game!" # Message to send to chat at the end of a game

# pgn_directory: "game_records" # A directory where PGN-format records of the bot's games are kept

matchmaking:
  allow_matchmaking: false    # Set it to 'true' to challenge other bots.
  challenge_variant: "random" # If set to 'random', the bot will choose one variant from the variants enabled in 'challenge.variants'.
  challenge_timeout: 30       # Create a challenge after being idle for 'challenge_timeout' minutes.
  challenge_initial_time: 60  # Initial time in seconds of the challenge.
  challenge_increment: 3      # Increment in seconds of the challenge.
# challenge_days: 2           # Days for correspondence challenge. If this option is enabled, a correspondence challenge will be created even if 'challenge_initial_time' is enabled.
  opponent_min_rating: 600    # Opponents rating should be above this value (600 is the minimum rating in lichess).
  opponent_max_rating: 4000   # Opponents rating should be below this value (4000 is the maximum rating in lichess).
  challenge_mode: "random"    # Set it to the mode in which challenges are sent. Possible options are 'casual', 'rated' and 'random'.

**Comment by TheYoBots** [comment]
As per the error I think there is an error in line 60:
```yml
    Threads:12               # Max CPU threads the engine can use.
```

To fix this I think you should change that line to:
```yml
    Threads: 12              # Max CPU threads the engine can use.
```

That is, add a space between the semicolon **`:`** and the number of threads **`12`**.

**Comment by thechipsss** [comment]
hmm ok'

**Comment by thechipsss** [comment]
but there is a problem i found my config.yml in google by link but i cant find in my folder..
![Screenshot 2022-07-09 205504](https://user-images.githubusercontent.com/91486076/178112125-27009b19-a0ef-430e-a393-251a3ddf71cd.jpg)

**Comment by MarkZH** [comment]
It's the second file named "config" with "Yaml Source File" as the type. If you click the View tab at the top of the window and select Show File Name Extensions, that will show "config.yml".

**Comment by thechipsss** [comment]
oh

**Comment by thechipsss** [comment]
i will test it right now thank you!

**Comment by thechipsss** [comment]
Thank you! it worked i will this now
