### ISSUE TITLE
Getting errors running the lichess-bot API

### ISSUE THREAD

**Issue by CallOn84** [ShailChoksi/lichess-bot#609]
I'm getting errors trying to run the lichess-bot API. The errors display when I try to convert my account to a bot account, showing this:

```
                    ERROR    There appears to be a syntax problem with your config.yml                     config.py:29
                             Traceback (most recent call last):
                               File "C:\Users\vieta\Desktop\Lc0\Lichess Bot\config.py", line 27, in
                             load_config
                                 CONFIG = yaml.safe_load(stream)
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packages\yam
                             l\__init__.py", line 125, in safe_load
                                 return load(stream, SafeLoader)
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packages\yam
                             l\__init__.py", line 81, in load
                                 return loader.get_single_data()
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packages\yam
                             l\constructor.py", line 49, in get_single_data
                                 node = self.get_single_node()
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packages\yam
                             l\composer.py", line 36, in get_single_node
                                 document = self.compose_document()
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packages\yam
                             l\composer.py", line 55, in compose_document
                                 node = self.compose_node(None, None)
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packages\yam
                             l\composer.py", line 84, in compose_node
                                 node = self.compose_mapping_node(anchor)
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packages\yam
                             l\composer.py", line 133, in compose_mapping_node
                                 item_value = self.compose_node(node, item_key)
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packages\yam
                             l\composer.py", line 84, in compose_node
                                 node = self.compose_mapping_node(anchor)
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packages\yam
                             l\composer.py", line 133, in compose_mapping_node
                                 item_value = self.compose_node(node, item_key)
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packages\yam
                             l\composer.py", line 64, in compose_node
                                 if self.check_event(AliasEvent):
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packages\yam
                             l\parser.py", line 98, in check_event
                                 self.current_event = self.state()
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packages\yam
                             l\parser.py", line 449, in parse_block_mapping_value
                                 if not self.check_token(KeyToken, ValueToken, BlockEndToken):
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packages\yam
                             l\scanner.py", line 116, in check_token
                                 self.fetch_more_tokens()
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packages\yam
                             l\scanner.py", line 251, in fetch_more_tokens
                                 return self.fetch_double()
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packages\yam
                             l\scanner.py", line 655, in fetch_double
                                 self.fetch_flow_scalar(style='"')
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packages\yam
                             l\scanner.py", line 666, in fetch_flow_scalar
                                 self.tokens.append(self.scan_flow_scalar(style))
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packages\yam
                             l\scanner.py", line 1149, in scan_flow_scalar
                                 chunks.extend(self.scan_flow_scalar_non_spaces(double, start_mark))
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packages\yam
                             l\scanner.py", line 1213, in scan_flow_scalar_non_spaces
                                 raise ScannerError("while scanning a double-quoted scalar", start_mark,
                             yaml.scanner.ScannerError: while scanning a double-quoted scalar
                               in "./config.yml", line 5, column 10
                             expected escape sequence of 8 hexadecimal numbers, but found 's'
                               in "./config.yml", line 5, column 15
                    ERROR    Quitting lichess-bot due to an error:                                   lichess-bot.py:733
                             Traceback (most recent call last):
                               File "C:\Users\vieta\Desktop\Lc0\Lichess Bot\lichess-bot.py", line
                             730, in <module>
                                 start_lichess_bot()
                               File "C:\Users\vieta\Desktop\Lc0\Lichess Bot\lichess-bot.py", line
                             708, in start_lichess_bot
                                 CONFIG = load_config(args.config or "./config.yml")
                               File "C:\Users\vieta\Desktop\Lc0\Lichess Bot\config.py", line 27, in
                             load_config
                                 CONFIG = yaml.safe_load(stream)
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packag
                             es\yaml\__init__.py", line 125, in safe_load
                                 return load(stream, SafeLoader)
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packag
                             es\yaml\__init__.py", line 81, in load
                                 return loader.get_single_data()
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packag
                             es\yaml\constructor.py", line 49, in get_single_data
                                 node = self.get_single_node()
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packag
                             es\yaml\composer.py", line 36, in get_single_node
                                 document = self.compose_document()
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packag
                             es\yaml\composer.py", line 55, in compose_document
                                 node = self.compose_node(None, None)
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packag
                             es\yaml\composer.py", line 84, in compose_node
                                 node = self.compose_mapping_node(anchor)
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packag
                             es\yaml\composer.py", line 133, in compose_mapping_node
                                 item_value = self.compose_node(node, item_key)
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packag
                             es\yaml\composer.py", line 84, in compose_node
                                 node = self.compose_mapping_node(anchor)
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packag
                             es\yaml\composer.py", line 133, in compose_mapping_node
                                 item_value = self.compose_node(node, item_key)
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packag
                             es\yaml\composer.py", line 64, in compose_node
                                 if self.check_event(AliasEvent):
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packag
                             es\yaml\parser.py", line 98, in check_event
                                 self.current_event = self.state()
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packag
                             es\yaml\parser.py", line 449, in parse_block_mapping_value
                                 if not self.check_token(KeyToken, ValueToken, BlockEndToken):
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packag
                             es\yaml\scanner.py", line 116, in check_token
                                 self.fetch_more_tokens()
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packag
                             es\yaml\scanner.py", line 251, in fetch_more_tokens
                                 return self.fetch_double()
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packag
                             es\yaml\scanner.py", line 655, in fetch_double
                                 self.fetch_flow_scalar(style='"')
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packag
                             es\yaml\scanner.py", line 666, in fetch_flow_scalar
                                 self.tokens.append(self.scan_flow_scalar(style))
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packag
                             es\yaml\scanner.py", line 1149, in scan_flow_scalar
                                 chunks.extend(self.scan_flow_scalar_non_spaces(double, start_mark))
                               File
                             "C:\Users\vieta\AppData\Local\Programs\Python\Python310\lib\site-packag
                             es\yaml\scanner.py", line 1213, in scan_flow_scalar_non_spaces
                                 raise ScannerError("while scanning a double-quoted scalar",
                             start_mark,
                             yaml.scanner.ScannerError: while scanning a double-quoted scalar
                               in "./config.yml", line 5, column 10
                             expected escape sequence of 8 hexadecimal numbers, but found 's'
                               in "./config.yml", line 5, column 15
```
I've attached the config.yml file for the bot. Maybe it's something wrong with how I configured the file or maybe I installed the requirements wrong? I'm not sure. [config.txt](https://github.com/ShailChoksi/lichess-bot/files/10221176/config.txt)

**Comment by CallOn84** [comment]
Thanks, that worked!
